### ISSUE TITLE
URL auto detection shows IP reporting types

### ISSUE THREAD

**Issue by charlie-kelly** [i-am-shodan/Microsoft-Abuse-Browser-Extension#1]
When the extension detects a URL, it defaults to the URL option correctly, however it shows the IP reporting types. I have to click on the 'URL' option for it to show me the correct types.

![image](https://github.com/i-am-shodan/Microsoft-Abuse-Browser-Extension/assets/9144251/6b7d0f63-5ede-42d0-8770-8e79595233da)

**Comment by i-am-shodan** [comment]
Pull and try again, I think its fixed

**Comment by charlie-kelly** [comment]
Confirmed - can be closed!
